// app/api/send-startup-form/route.ts
import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: NextRequest) {

    async function sendConfirmationEmail(
        transporter: nodemailer.Transporter,
        recipientEmail: string,
        founderName: string,
        startupName: string
      ) {
        const mailOptions = {
          from: `"Aventure Studio" <${process.env.EMAIL_USER || "idris@aventurestud.io"}>`,
          to: recipientEmail,
          subject: `We've received your submission for ${startupName}`,
          html: `
            <html>
              <body>
                <h2>Thank you for your submission, ${founderName}!</h2>
                <p>We've successfully received your application for <strong>${startupName}</strong>.</p>
                <p>Our team will review your submission and get back to you soon.</p>
                <br/>
                <p>Best regards,</p>
                <p>The Aventure Studio Team</p>

                <footer style="margin-top: 20px; font-size: 12px; color: #888;">
                     <img src="https://www.aventurestud.io/assets/AVSLogo.png" alt="Aventure Studio Logo" />

                  <p>This email was generated by <a href="https://aventurestud.io">aventurestud.io</a></p>
                  <p>&copy; ${new Date().getFullYear()} Aventure Studio</p>
              </body>
            </html>
          `,
          text: `
            Thank you for your submission, ${founderName}!
            We've successfully received your application for ${startupName}.
            Our team will review your submission and get back to you soon.
            
            Best regards,
            The Aventure Studio Team
          `
        };
      
        return transporter.sendMail(mailOptions);
      }
  try {
    const formData = await req.formData();
    
    // Extract form fields
    const founderName = formData.get('founderName') as string;
    const email = formData.get('email') as string;
    const startupName = formData.get('startupName') as string;
    const website = formData.get('website') as string;
    const description = formData.get('description') as string;
    const problem = formData.get('problem') as string;
    const customers = formData.get('customers') as string;
    const revenue = formData.get('revenue') as string;
    const notes = formData.get('notes') as string;
    const startupStage = formData.get('startupStage') as string;
    const existingFunding = formData.get('existingFunding') as string;
    const support = formData.get('supportType') as string;
    
    // Extract file if exists
    const file = formData.get('file') as File | null;

    // Configure transporter (same as your working code)
    const transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 587,
      secure: false,
      auth: {
        user: process.env.EMAIL_USER || "idris@aventurestud.io",
        pass: process.env.EMAIL_PASS || "uzam xobg qgqs aewa",
      },
      tls: {
        rejectUnauthorized: false,
      },
      connectionTimeout: 10000,
    });

    // Email content
    const emailSubject = `New Startup Submission from ${founderName}`;
    
    const textContent = `
Founder: ${founderName}
Email: ${email}
Startup Name: ${startupName}
Website: ${website}
Startup Stage: ${startupStage}
Funding: ${existingFunding}
Support Needed: ${support}

Description: ${description}
Problem: ${problem}
Customers: ${customers}
Revenue Model: ${revenue}
Notes: ${notes}
    `;

    // HTML version (optional but recommended)
    // const emailSubject = `New Startup Submission from ${founderName}`;

    const htmlContent = `
    <html>
      <head>
        <style>
          body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f7;
            margin: 0;
            padding: 0;
            color: #333;
          }
          .container {
            max-width: 600px;
            margin: 40px auto;
            background-color: #fff;
            border-radius: 8px;
            padding: 30px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.05);
            border: 1px solid #ddd;

          }
          .header {
            background-color: #fff;
            padding: 20px;
            border-top-left-radius: 8px;
            border-top-right-radius: 8px;
            color: black;
            text-align: center;

            border-bottom: 1px dashed #ddd;
          }
          .header h1 {
            margin: 0;
            font-size: 22px;
          }
          .section {
            margin-top: 20px;
          }
          .section h3 {
            color: #0052cc;
            margin-bottom: 5px;
          }
          .section p {
            margin: 0 0 10px;
          }
             .logo {
            max-width: 150px;
            margin-bottom: 20px;
          }
          .footer {
            text-align: center;
            font-size: 13px;
            color: #888;
            margin-top: 30px;
            border-top: 1px solid #ddd;


            padding-top: 15px;
            
          }
          a {
            color: #0052cc;
            text-decoration: none;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>New Startup Submission</h1>
            <img src="https://www.aventurestud.io/assets/AVSLogo.png" alt="Aventure Studio Logo" class="logo"/>
            <p>via <a href="https://aventurestud.io" style="color: #ffffff; text-decoration: underline;">aventurestud.io</a></p>
          </div>
    
          <div class="section">
            <h3>Founder Info</h3>
            <p><strong>Founder:</strong> ${founderName}</p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Startup Name:</strong> ${startupName}</p>
            <p><strong>Website:</strong> ${website}</p>
          </div>
    
          <div class="section">
            <h3>Startup Details</h3>
            <p><strong>Stage:</strong> ${startupStage}</p>
            <p><strong>Funding:</strong> ${existingFunding}</p>
            <p><strong>Support Needed:</strong> ${support}</p>
          </div>
    
          <div class="section">
            <h3>Description</h3>
            <p>${description.replace(/\n/g, '<br>')}</p>
          </div>
    
          <div class="section">
            <h3>Problem</h3>
            <p>${problem.replace(/\n/g, '<br>')}</p>
          </div>
    
          <div class="section">
            <h3>Target Customers</h3>
            <p>${customers.replace(/\n/g, '<br>')}</p>
          </div>
    
          <div class="section">
            <h3>Revenue Model</h3>
            <p>${revenue.replace(/\n/g, '<br>')}</p>
          </div>
    
          <div class="section">
            <h3>Additional Notes</h3>
            <p>${notes.replace(/\n/g, '<br>')}</p>
          </div>
    
          <div class="footer">
                         <img src="https://www.aventurestud.io/assets/AVSLogo.png" alt="Aventure Studio Logo" class="logo"/>

            This email was generated by <a href="https://aventurestud.io">aventurestud.io</a> &bull; Copyright © ${new Date().getFullYear()}
          </div>
        </div>
      </body>
    </html>
    `;
    

    // Prepare mail optionshello@aventurestud.io,jt@aventurestud.io,dm@aventurestud.io,
    const mailOptions: nodemailer.SendMailOptions = {
      from: email,
      to: process.env.RECEIVER_EMAIL || "idris@aventurestud.io",
      subject: emailSubject,
      text: textContent,
      html: htmlContent,
      replyTo: email,
    };

    // Handle file attachment if exists
    if (file) {
      const arrayBuffer = await file.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      
      mailOptions.attachments = [
        {
          filename: file.name,
          content: buffer,
          encoding: 'base64',
        },
      ];
    }

    // Send email
    const info = await transporter.sendMail(mailOptions);

     // Send confirmation to the submitter
     const confirmationEmailPromise = sendConfirmationEmail(
        transporter,
        email,
        founderName,
        startupName
      );
  
      // Wait for both emails to send
      const [teamResult, confirmationResult] = await Promise.all([
        info,
        confirmationEmailPromise
      ]);
  
      console.log('Both emails sent successfully');
      
    return NextResponse.json({ 
      success: true, 
      message: "Startup form submitted successfully!",
    //   messageId: info.messageId
      messageIds: {
        team: info.messageId,
        confirmation: confirmationResult.messageId
      }
    });

  } catch (error) {
    console.error('Error submitting startup form:', error);
    return NextResponse.json(
      { 
        success: false, 
        message: "Failed to submit startup form", 
        error: error instanceof Error ? error.message : 'Unknown error' 
      },
      { status: 500 }
    );
  }
}